- name: Create Kafka Topics
  hosts: kafka_brokers
  vars:
    kafka_home: /opt/kafka
    zookeeper_host: "http://brokerURL:2181"
    kafka_topics:
      - name: topic_1
        partitions: 3
        replication: 1
      - name: topic_2
        partitions: 1
        replication: 1
  tasks:
    - name: Create Kafka Topics
      shell: >
        {{ kafka_home }}/bin/kafka-topics.sh
        --create
        --if-not-exists
        --zookeeper {{ zookeeper_host }}
        --partitions {{ item.partitions }}
        --replication-factor {{ item.replication }}
        --topic {{ item.name }}
      loop: "{{ kafka_topics }}"
      run_once: true
      register: topic_creation
      changed_when: "'Created' in topic_creation.stdout"
